grafana:
  resources: 
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 200m
      memory: 600Mi
  enabled: true
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-cluster
      kubernetes.io/force-ssl-redirect: "true"
      kubernetes.io/ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
    enabled: true
    hosts:
    - "grafana.{{.DomainName}}"
    tls:
    - hosts:
      - "grafana.{{.DomainName}}"
      secretName: cert-grafana
  plugins:
  - vertamedia-clickhouse-datasource
  - grafana-clickhouse-datasource
  - volkovlabs-echarts-panel
  - marcusolsson-json-datasource
  - camptocamp-prometheus-alertmanager-datasource
  - volkovlabs-variable-panel
  sidecar:
    dashboards:
      enabled: true
      folderAnnotation: grafana_folder
      provider:
        foldersFromFilesStructure: true
        allowUiUpdates: true
    datasources:
      enabled: true
  postgresql:
    enabled: true
  database: 
    type: postgres
    host: prometheus-postgresql:5432
    name: postgres
    ssl_mode: disable
    user: postgres
    password: $__file{/etc/secrets/postgresql/postgres-password}
    secretMount:
      name: postgresql-mount
      mountPath: /etc/secrets/postgresql
      secretName: prometheus-postgresql
      readOnly: true
prometheus:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-cluster
      kubernetes.io/force-ssl-redirect: "true"
      kubernetes.io/ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
    enabled: true
    hosts:
    - "prometheus.{{.DomainName}}"
    paths:
    - /
    tls:
    - hosts:
      - "prometheus.{{.DomainName}}"
      secretName: cert-prometheus
  prometheusSpec:
    resources: 
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 4Gi
    enableRemoteWriteReceiver: true
    externalLabels:
      cluster_name: capten-controlplane
alertmanager:
  alertmanagerSpec:
    resources: 
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 150Mi
    alertmanagerConfigMatcherStrategy:
      type: None
prometheusOperator:
  resources: 
    requests:
      cpu: 100m
      memory: 150Mi
    limits:
      cpu: 200m
      memory: 280Mi
kube-state-metrics:
  resources: 
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 130Mi
prometheus-node-exporter:
  resources: 
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 150Mi
