ports:
  traefik:
    expose: false
    port: 9000
  web:
    expose: true
    port: 8000
    nodePort: 32080
  websecure:
    expose: true
    port: 8443
    nodePort: 32443
service:
  enabled: "true"
{{if eq .ClusterType "talos"}}
  type: NodePort
{{else if eq .ClusterType "cloud-managed"}}
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
{{end}}
resources: 
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 150Mi
