AwsAccessKey: ""
AwsSecretKey: ""
AlbName: "talosalb"
PrivateSubnet: "10.0.1.0/24"
Region: "us-west-1"
SecurityGroupName: "talossg"
VpcCidr: "10.0.0.0/16"
VpcName: "talosvpc"
InstanceType: "t2.medium"
NodeMonitoringEnabled: "false"
MasterCount: "3"
WorkerCount: "3"
TraefikHttpPort: "32080"
TraefikHttpsPort: "32443"
#GlobalValues:
#  StringValues:
#    ingress.hostname: "test.optimizer.com"
#  Values:
#    "test": "test"
PostInstall:
  - Name: "openebs-jiva"
    ChartName: "tools/openebs-jiva"
    RepoName: "tools"
    RepoURL: "https://kube-tarian.github.io/helmrepo-supporting-tools"
    Namespace: "openebs-jiva"
    ReleaseName: "openebs-jiva"
    Version: "1.0.5"
    CreateNamespace: true
    MakeNsPrivilege: true
  - Name: "traefik"
    ChartName: "traefik/traefik"
    RepoName: "traefik"
    RepoURL: "https://traefik.github.io/charts"
    Namespace: "traefik"
    ReleaseName: "traefik"
    Version: "20.8.0"
    CreateNamespace: true
    Override:
      Values:
        "service.type": NodePort
        # note: need to provide the case-sensitive key as part of value
        "ports.websecure.nodePort": ports.websecure.nodePort|32443
        "ports.web.nodePort": ports.web.nodePort|32080
  - Name: "temporal"
    ChartName: "tools/temporal"
    RepoName: "tools"
    RepoURL: "https://kube-tarian.github.io/helmrepo-supporting-tools"
    Namespace: "capten"
    ReleaseName: "temporal"
    Version: "0.1.1"
    CreateNamespace: false
  - Name: "loki"
    ChartName: "grafana/loki-stack"
    RepoName: "grafana"
    RepoURL: "https://grafana.github.io/helm-charts"
    Namespace: "observability"
    ReleaseName: "loki-test"
    CreateNamespace: true
    Override:
      StringValues:
        'grafana.ingress.annotations.cert-manager\.io\/cluster-issuer': "letsencrypt-prod-cluster"
        'grafana.ingress.annotations.kubernetes\.io\/force-ssl-redirect': "true"
        'grafana.ingress.annotations.kubernetes\.io\/ssl-redirect': "true"
        'grafana.ingress.annotations.kubernetes\.io\/tls-acme': "true"
      Values:
        "grafana.enabled": true
        "grafana.ingress.enabled": true
        "grafana.ingress.hosts": '{"grafana.dev.optimizor.app"}'
        "prometheus.enabled": true
        "grafana.sidecar.datasources.enabled": true
        "grafana.sidecar.dashboards.enabled": true
  - Name: "cert-manager"
    ChartName: "jetstack/cert-manager"
    RepoName: "jetstack"
    RepoURL: "https://charts.jetstack.io"
    Namespace: "cert-manager"
    ReleaseName: "cert-manager"
    Version: "v1.11.0"
    CreateNamespace: true
    Override:
      Values:
        "installCRDs": true
  - Name: "kad"
    ChartName: "kad/kad"
    RepoName: "kad"
    RepoURL: "https://kube-tarian.github.io/kad"
    Namespace: "default"
    ReleaseName: "kad"
    Version: "0.1.16"
    CreateNamespace: true
    Override:
      Values:
        "ingressroute.mtls.enabled": true
    SecretInfos:
      - FilePath: "./intermediate/cert-chain.pem"
        Key: "ingressroute.mtls.caCrt"
      - FilePath: "./server/server.crt"
        Key: "ingressroute.mtls.tlsCrt"
      - FilePath: "./server/server.key"
        Key: "ingressroute.mtls.tlsKey"
  - Name: "signoz"
    ChartName: "signoz/signoz"
    RepoName: "signoz"
    RepoURL: "https://charts.signoz.io"
    Namespace: "observability"
    ReleaseName: "signoz"
    CreateNamespace: true

